server:
  port: 8080

spring:
  datasource:
    username: root
    password: e20yEIOd6Ugl
    url: jdbc:mysql://47.111.247.214:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:com.example.mapper/*Mapper.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug